using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using group_proj.Main;

namespace group_proj.Items
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class wndItems : Window
    {
        clsItemsLogic logic = new clsItemsLogic();
        clsItemsSQL sqlQueries;
        DataGrid data;
        List<clsItem> dataInfo;

        public wndItems()
        {
            InitializeComponent();
            sqlQueries = new clsItemsSQL();
            data = new DataGrid();
            DataContext = this;
            getItemsList();
        }

        public void getItemsList()
        {
            try
            {
                itemdescdatagrid.ItemsSource = logic.getItemsList();
            }
            catch (Exception)
            {

                throw;
            }
        }

        private void ItemDescDataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            try
            {
                data = sender as DataGrid;
                if(data.Items.Count != 0)
                {
                    dataInfo = data.SelectedItems.Cast<clsItem>().ToList();
                    ItemSelectedCode.Text = dataInfo[0].ItemCode;
                    ItemDescUpdate.Text = dataInfo[0].ItemDesc;
                    CostUpdate.Text = dataInfo[0].Cost.ToString();
                }
            }
            catch (Exception ex)
            {

                MessageBox.Show(MethodInfo.GetCurrentMethod().DeclaringType.Name + "." + MethodInfo.GetCurrentMethod().Name + " -> " + ex.Message); 
            }
        }

        private void addItem_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                //Will be used to add items to the database
                logic.addItem(addItem.Text, addCost.Text);
                resetDG();
            }
            catch (Exception ex)
            {
                MessageBox.Show(MethodInfo.GetCurrentMethod().DeclaringType.Name + "." + MethodInfo.GetCurrentMethod().Name + " -> " + ex.Message);
            }
        }

        private void updateItem_Click(object sender, RoutedEventArgs e)
        {

            try
            {
                //When applicable this method call updates the rows in the data grid.
                logic.updateItemRow(ItemSelectedCode.Text, ItemDescUpdate.Text, CostUpdate.Text);
                resetDG();
            }
            catch (Exception ex)
            {
                MessageBox.Show(MethodInfo.GetCurrentMethod().DeclaringType.Name + "." + MethodInfo.GetCurrentMethod().Name + " -> " + ex.Message);
            }

        }

        /// <summary>
        /// Deletes item from the database using the item code.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void deleteItem_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                MessageBoxResult result = MessageBox.Show("Deleting this row will permanently delete it from the database. Would you like to continue?", "Alert", MessageBoxButton.YesNo, MessageBoxImage.Warning);
                if (result == MessageBoxResult.Yes)
                {
                    int checkRow = logic.checkInvoice(ItemSelectedCode.Text);
                    if(checkRow == 0)
                    {
                       logic.deleteItem(ItemSelectedCode.Text);
                       resetDG();
                    }
                    else
                    {
                        MessageBox.Show("Item cannot be deleted. The item is currently on invoice " + checkRow);
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(MethodInfo.GetCurrentMethod().DeclaringType.Name + "." + MethodInfo.GetCurrentMethod().Name + " -> " + ex.Message);
            }
        }

        /// <summary>
        /// Upon returning from available items from database list. The main window will reflect the changes made in the window items interface. 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void MainWindow_Click(object sender, RoutedEventArgs e)
        {
            this.Close();
        }

        private void Itemdescdatagrid_AutoGeneratedColumns(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            e.Column.Header = ((PropertyDescriptor)e.PropertyDescriptor).DisplayName;
        }

        private void resetDG()
        {
            itemdescdatagrid.ItemsSource = null;
            itemdescdatagrid.ItemsSource = logic.getItemsList();
            ItemSelectedCode.Text = " ";
            ItemDescUpdate.Text = " ";
            CostUpdate.Text = " ";
            addItem.Text = " ";
            addCost.Text = " ";
        }
    }
}
